import type { ClubScenario } from "./scenario-types";

export const defaultClubs: ClubScenario[] = [
  {
    id: "club-1",
    imageSrc: "/photos/club-hero-1.jpg",
    partner: "Che Fico",
    club: "Cheese & Wine",
    clubState: "active",
    cohortTimeline: "announced",
    cohortCadence: "monthly",
    fulfillmentMethods: ["delivery"],
    offerMain: 120,
    offerAddon: 0,
    address1: "CA",
    address2: null,
    membershipState: "active",
    membershipFulfillment: "delivery",
    membershipAddress: ["CA"],
    membershipErrors: ["payment error"],
    gifted: false,
  },
  {
    id: "club-2",
    imageSrc: "/photos/club-hero-2.jpg",
    partner: "Che Fico",
    club: "Cheese & Wine",
    clubState: "active",
    cohortTimeline: "announced",
    cohortCadence: "monthly",
    fulfillmentMethods: ["delivery"],
    offerMain: 120,
    offerAddon: 0,
    address1: "CA",
    address2: null,
    membershipState: "paused",
    membershipFulfillment: "delivery",
    membershipAddress: ["CA"],
    membershipErrors: ["payment error"],
    gifted: true,
  },
  {
    id: "club-3",
    imageSrc: "/photos/club-hero-3.jpg",
    partner: "Domestique",
    club: "Wine Club",
    clubState: "stopped",
    cohortTimeline: "fulfilled",
    cohortCadence: "monthly",
    fulfillmentMethods: ["delivery"],
    offerMain: 100,
    offerAddon: 0,
    address1: "CA",
    address2: null,
    membershipState: "cancelled",
    membershipFulfillment: "delivery",
    membershipAddress: ["CA"],
    membershipErrors: [],
    gifted: false,
  },
  {
    id: "club-4",
    imageSrc: "/photos/club-hero-4.jpg",
    partner: "Slanted Door",
    club: "Supper Club",
    clubState: "stopped",
    cohortTimeline: "fulfilled",
    cohortCadence: "quarterly",
    fulfillmentMethods: ["pickup"],
    offerMain: 150,
    offerAddon: 0,
    address1: "CA",
    address2: null,
    membershipState: "cancelled",
    membershipFulfillment: "pick-up",
    membershipAddress: ["CA"],
    membershipErrors: [],
    gifted: true,
  },
  {
    id: "club-5",
    imageSrc: "/photos/club-hero-5.jpg",
    partner: "Saigon Social",
    club: "Cheese & Wine",
    clubState: "stopped",
    cohortTimeline: "fulfilled",
    cohortCadence: "monthly",
    fulfillmentMethods: ["delivery"],
    offerMain: 90,
    offerAddon: 0,
    address1: "CA",
    address2: null,
    membershipState: "cancelled",
    membershipFulfillment: "delivery",
    membershipAddress: ["CA"],
    membershipErrors: ["payment error"],
    gifted: false,
  },
];
